FROM node:22-slim AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-slim

WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist/Sistema_Almace ./dist/Sistema_Almace
EXPOSE 4000
CMD ["npm", "run", "serve:ssr:Sistema_Almace"]
